version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: mackie86/ecommercereact
    docker:
      - image: node:alpine

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build React App
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build/

  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-main:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
